### ISSUE TITLE
Getting a weird box around categories when hovering

### ISSUE THREAD

**Issue by Lokawn** [elviosak/plugin-wingmenu#5] opened 2022-07-17 05:06 UTC
The menu starts normally but when category is changed by hovering a weird box appears around all category text.
Does not appear around apps list or logout menu.

But when using keyboard for navigation it is present on logout menu, apps list and categories depending on which is being changed.

![image](https://user-images.githubusercontent.com/39772448/179384655-6e022d07-78ee-4639-89ca-19e3cd780698.png)

Using keyboard for navigation.
![image](https://user-images.githubusercontent.com/39772448/179384666-ddf5df87-1f4d-4706-800a-121f81fb7477.png)

On archlinux, using latest commit with Kvantum Engine and MateriaDark theme, system theme is selected in LxQt themes.

The Menu looks super amazing btw.

**Comment by stefonarch** [comment] 2022-07-17 08:58
The categories are qtoolbuttons and at the moment they get styled by themes like the 2 titles when right clicking a plugin on the panel.
System theme uses plain widget settings, so with breeze or oxygen you get centered items for example.

I'm updating the themes atm, but just removing  this block all themes work already better:

```
 QMenu QToolButton {
    background-color: #003a55;
    padding: 5px;
    border: none;
    color: #53bcec;
    font: bold italic;
}
```

This is the draft for Ambiance in `lxqt-panel.qss`:
```
/*
Wing menu plugin
*/

#WingMenuPlugin QWidget{
	background:#43423c;
}
#WingMenuPlugin QToolButton,#WingMenuPlugin ApplicationsView,#WingMenuPlugin ApplicationsView::item {
    color: #f2f1f0;
    background-color: #43423c;
    font:normal;
}
#WingMenuPlugin QToolButton:hover,#WingMenuPlugin ApplicationsView::item:hover {
    color: #f2f1f0;
    background:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f88657, stop:1 #eb7140);
}
```

**Comment by stefonarch** [comment] 2022-07-18 20:32
I think this can be closed as it's due to widget style and  no theming.
(theming is on the way; https://github.com/lxqt/lxqt-themes/tree/wing-menu-fixes )

**Comment by elviosak** [comment] 2022-07-19 15:16
Alright, closing as it is related to theming, probably also because of Qt' hover bug.

**Comment by Lokawn** [comment] 2022-07-24 10:54
The box is also present with Windows Qt Style.

![screenshot-e327a502](https://user-images.githubusercontent.com/39772448/180643849-fc858b06-6121-4253-8917-c668b6cab8ac.png)

**Comment by stefonarch** [comment] 2022-07-24 11:30
Did you update your theme? 
https://github.com/lxqt/lxqt-themes/tree/wing-menu-fixes

**Comment by Lokawn** [comment] 2022-07-24 12:40
> Did you update your theme?

Yes. There are no boxes with updated themes with **Kvantum, Fusion, Windows** Qt Styles and **Fusion** Qt Style with **System** LxQt theme.

But **Kvantum** and **Windows** Qt Style with **System** LxQt theme still show those boxes around categories.

With the updated themes with all Qt Styles I tried (Kvantum, Fusion, Windows) there is no indication of selected category when using keyboard for navigation.

![image](https://user-images.githubusercontent.com/39772448/180647365-83957207-84ea-41aa-9f58-77126e871080.png)
The above picture shows Ambiance LxQt theme and Fusion Qt Style.

**Comment by stefonarch** [comment] 2022-07-24 13:33
There is no keyboard navigation for categories, it's only for the application view afaik.

I cannot reproduce any of yours at the moment, will look more into it. Ambiance/Fusion here:
![screenshot-2ea8e567](https://user-images.githubusercontent.com/10681413/180649338-af7fe091-63dd-480a-87aa-66de69ece6e2.png)

EDIT: O there is, but highlighting doesn't work with it, that's why I didn't see it.

**Comment by Lokawn** [comment] 2022-07-24 14:39
> EDIT: O there is, but highlighting doesn't work with it, that's why I didn't see it.

Highlighting works with **System** LxQt Theme.

**Comment by stefonarch** [comment] 2022-07-24 14:50
True, saw  it now. Not sure if this can be fixed by themes. I see that with keyboard navigation the colors  change, while with mouse no.
Maybe a border-color for selected push buttons will do. Will make some tests.

**Comment by stefonarch** [comment] 2022-07-24 16:00
>But Kvantum and Windows Qt Style with System LxQt theme still show those boxes around categories.

 that's why in the README here fusion is recommended with system theme (which is a plain widget theme and with breeze for example you get eliding text in panel buttons)

**Comment by stefonarch** [comment] 2022-07-24 16:11
No way, I tried border and added also `QToolButton:selected,QToolButton:on` but no result. There is something at the base for selecting categories which is different  with keyboard arrows.

**Comment by elviosak** [comment] 2022-07-24 16:36
I replicated with Kvantum, but was able to remove on kvantum config Miscellaneous > Remove focus rectangles, then restarting panel.
i'll try to remove them without relying on themes.

**Comment by stefonarch** [comment] 2022-07-24 16:46
> i'll try to remove them without relying on themes.

I tried also to remove all QToolButton styling, to no avail.

**Comment by elviosak** [comment] 2022-07-24 16:54
@Lokawn @stefonarch Can you check if the last commit fixes it?

**Comment by stefonarch** [comment] 2022-07-24 17:20
With "system" theme all widgets are ok without boxes.
With all other themes nothing changes, tried again removing QToolButton stylings, borders come back but no keyboard nav highlighting.

**Comment by Lokawn** [comment] 2022-07-24 17:46
Yes System theme is working flawlessly with all widget styles.

Kvantum with System theme.
https://user-images.githubusercontent.com/39772448/180659517-3b4f08a1-7d65-48ea-8224-1799bc722d16.mp4

**Comment by elviosak** [comment] 2022-07-24 18:11
> With all other themes nothing changes, tried again removing QToolButton stylings, borders come back but no keyboard nav highlighting.

But the "weird boxes "are gone?

No highlighting on buttons is due to the style that other themes apply so qtoolbutton always appear toggled so on the menu there's no visual indication when they are selected.

**Comment by stefonarch** [comment] 2022-07-24 18:35
> Kvantum with System theme.

same issue as breeze and oxygen: centered items

> But the "weird boxes "are gone?

With all other themes I didn't saw boxes before too. Removing styling only of buttons brings a kind of boxes/borders/lines back but no highlighting.

> No highlighting on buttons is due to the style that other themes apply

Highlighting works perfectly in all themes with mousecursor, but doesn't when keyboard arrows are used.

**Comment by stefonarch** [comment] 2022-07-24 18:51
Oops. I forgot to remove `all` qtoolbuttons style (the one who styles menu titles when right clicking on a panel plugin).
So now this takes clean widget style and keyboard navigation is working. This is "Valendas" style.

https://user-images.githubusercontent.com/10681413/180661609-0f70d5cf-0386-485f-b8ab-0a555a65d47b.mp4

**Comment by stefonarch** [comment] 2022-07-24 19:03
Hover styling is doable but some weird with mouse. Here first mouse, then keyboard:

https://user-images.githubusercontent.com/10681413/180662031-70ead541-4ba5-4b99-a913-3ecfcbe90eea.mp4

**Comment by elviosak** [comment] 2022-07-24 19:10
All selections(mouse hover/click and keyboard) are done by toggling the button so  would it be better to set the styling the same for hover and checked/pressed? Or at least similar colors?

**Comment by stefonarch** [comment] 2022-07-24 19:27
O very nice! I didn't test _checked_ it's  enough for both mouse and keyboard. no difference anymore.

```
#WingMenuPlugin QToolButton:checked,#WingMenuPlugin ApplicationsView::item:hover,#WingMenuPlugin ApplicationsView::item:selected {
    background-color: #c3d3c9;
    color: black;

}

```
Will update all themes.

**Comment by elviosak** [comment] 2022-07-25 01:22
forgot to close it, fixed by https://github.com/slidinghotdog/plugin-wingmenu/commit/81e9f3a1e6bb963ccc1ed60109152072f79004fb

**Closed as completed by elviosak** 2022-07-25 01:22 UTC

**Comment by stefonarch** [comment] 2022-07-25 09:26
Some boxes/borders are hard to kill. With windows widget style in all themes  those dotted borders are shown when navigating with keyboard, and icon background is different, tried to remove them with `border:none` but no effect:

![schermata-25 lug 11:11](https://user-images.githubusercontent.com/10681413/180743824-91efa07b-e43e-4ffa-8860-724afdee03a0.png)

 With fusion similar happens and is not seen in all themes, still only keyboard:

![schermata-25 lug 11:20](https://user-images.githubusercontent.com/10681413/180744301-6d39c734-37d0-4e2e-8c66-1a23d733f0a8.png)
